<a href="https://colab.research.google.com/github/varasrisiri/Machine-Learning-Course-Part_2/blob/main/4.1.4_Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy Library

In [2]:
import numpy as np


**Matrix Addition**

Two matrices can be added only if they have the same shape

In [9]:
#creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

print(A)

[[2 3]
 [4 5]]


In [10]:
print(B)

[[6 7]
 [8 9]]


In [13]:
A.shape

(2, 2)

In [15]:
B.shape

(2, 2)

Adding two Matrices

In [16]:
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [17]:
#creating two matrices with random values
matrix_1 = np.random.randint(20,size = (3,3))
matrix_2 = np.random.randint(30, size = (3,3))


In [19]:
print(matrix_1)

[[ 1  4  9]
 [ 2 13  3]
 [ 8 12  1]]


In [20]:
print(matrix_2)

[[25 22  1]
 [18 12 17]
 [ 5 17  3]]


In [21]:
sum = np.add(matrix_1,matrix_2)

In [22]:
print(sum)

[[26 26 10]
 [20 25 20]
 [13 29  4]]


In [24]:
#creating two matrices with random values
matrix_3 = np.random.randint(20,size = (3,3))
matrix_4 = np.random.randint(30, size = (3,4))


In [25]:
sum_2 = np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

THIS ERROR IS BECAUSE THE SHAPE OF matrix_3,matrix_4 ARE DIFFERENT

**Matrix Subtraction**

In [26]:
#creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [27]:
print(A)


[[2 3]
 [4 5]]


In [28]:
print(B)

[[6 7]
 [8 9]]


In [29]:
Difference = A - B

In [30]:
print(Difference)

[[-4 -4]
 [-4 -4]]


In [32]:
#creating two matrices with random values
matrix_A = np.random.randint(20,size = (3,3))
matrix_B = np.random.randint(30, size = (3,3))

In [33]:
print(matrix_A)

[[ 0 19 13]
 [14 15 16]
 [18  0  2]]


In [34]:
print(matrix_B)

[[19 28 20]
 [16 26  4]
 [ 6  7  5]]


In [35]:
diff = np.subtract(matrix_A,matrix_B)

In [36]:
print(diff)

[[-19  -9  -7]
 [ -2 -11  12]
 [ 12  -7  -3]]


In [37]:
#creating two matrices with random values
matrix_C = np.random.randint(20,size = (3,3))
matrix_D = np.random.randint(30, size = (3,4))


In [38]:
print(matrix_C)

[[ 5  5 16]
 [16 15 12]
 [10  6 19]]


In [39]:
print(matrix_D)

[[23 24 24 25]
 [14  4 17  9]
 [17 28 29 18]]


In [40]:
diff = np.subtract(matrix_C,matrix_D)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

**Multiplying a matrix by a scalar**

In [41]:
x = 5
y = np.random.randint(10, size = (3,3))

print(y)

[[2 0 4]
 [2 3 3]
 [3 9 2]]


In [42]:
product = np.multiply(x,y)

In [43]:
print(product)

[[10  0 20]
 [10 15 15]
 [15 45 10]]


**Multiplying two matrices**

In [44]:
#creating two matrices with random values
matrix_1 = np.random.randint(5,size = (3,3))
matrix_2 = np.random.randint(5, size = (3,4))

In [45]:
print(matrix_1)

[[4 4 3]
 [2 1 3]
 [3 1 1]]


In [46]:
print(matrix_4)

[[29 18 13 26]
 [28  5 19 20]
 [17 13 23 12]]


In [47]:
product = np.dot(matrix_1,matrix_2)

In [48]:
print(product)

[[16 12 11 20]
 [14  3  7 14]
 [ 7  3  7  6]]


In [49]:
product.shape

(3, 4)

In [50]:
#creating two matrices with random values
matrix_3 = np.random.randint(5,size = (3,3))
matrix_4 = np.random.randint(5, size = (4,4))

In [51]:
product = np.dot(matrix_3,matrix_4)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

In [56]:
#creating two matrices with random values
matrix_5 = np.random.randint(5,size = (3,3))
matrix_6 = np.random.randint(5, size = (3,3))

In [57]:
print(matrix_5)

[[1 0 3]
 [1 2 3]
 [3 0 2]]


In [58]:
print(matrix_6)

[[0 2 4]
 [1 1 4]
 [2 3 4]]


In [59]:
product = np.multiply(matrix_5,matrix_6)

In [60]:
print(product)

[[ 0  0 12]
 [ 1  2 12]
 [ 6  0  8]]
