<a href="https://colab.research.google.com/github/varasrisiri/Machine-Learning-Course-Part_2/blob/main/4.1.3_Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



Creating a Matrix using Numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)


[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,19]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 19]]


In [8]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [10]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.24805222 0.98004901 0.12425828]
 [0.26458665 0.90778008 0.66791184]
 [0.07435549 0.14208974 0.36435383]]


In [14]:
#creating matrix with random integers
random_integer_matrix = np.random.randint(100, size = (4,5))
print(random_integer_matrix)

[[80 18 58 14 95]
 [44 28 91 37 40]
 [71  5 91 79 48]
 [19 42  6  8 49]]


Matrix with all the values as 1


In [15]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
matrix_3 = np.ones((10,10), dtype = int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix on Zero Matrix

In [17]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [19]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
identity_matrix = np.eye(6,6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Transpose of Matrix

In [21]:
#matrix with random integer values
a = np.random.randint(100, size = (4,5))
print(a)

[[65 87  0 56 19]
 [15 94 55 91 29]
 [ 7  5 36 47 81]
 [32 13 74  5 74]]


In [23]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[65 15  7 32]
 [87 94  5 13]
 [ 0 55 36 74]
 [56 91 47  5]
 [19 29 81 74]]
